language: python
sudo: false
python:
  - "2.6"
  - "2.7"
before_install:
  pip install codecov
install:
  - python setup.py develop
  - python setup.py test
script:
  - py.test
after_success:
  codecov
